/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef db_wallet_sessionid_TYPES_H
#define db_wallet_sessionid_TYPES_H

#include <iosfwd>
#include "network/protocol/protocol.h"
#include "network/protocol/net_message.h"
#include "util/TToString.h"

namespace dbc {

    class db_wallet_sessionid;

    typedef struct _db_wallet_sessionid__isset {
        _db_wallet_sessionid__isset() : multisig_signers(false) {}
        bool multisig_signers : 1;
    } _db_wallet_sessionid__isset;

    class db_wallet_sessionid : public virtual ::apache::thrift::TBase {
    public:

        db_wallet_sessionid(const db_wallet_sessionid&);
        db_wallet_sessionid& operator=(const db_wallet_sessionid&);
        db_wallet_sessionid() : rent_wallet(), session_id() {
        }

        virtual ~db_wallet_sessionid() throw();
        std::string rent_wallet;
        std::string session_id;
        std::vector<std::string>  multisig_signers;

        _db_wallet_sessionid__isset __isset;

        void __set_rent_wallet(const std::string& val);

        void __set_session_id(const std::string& val);

        void __set_multisig_signers(const std::vector<std::string>& val);

        bool operator == (const db_wallet_sessionid& rhs) const
        {
            if (!(rent_wallet == rhs.rent_wallet))
                return false;
            if (!(session_id == rhs.session_id))
                return false;
            if (__isset.multisig_signers != rhs.__isset.multisig_signers)
                return false;
            else if (__isset.multisig_signers && !(multisig_signers == rhs.multisig_signers))
                return false;
            return true;
        }
        bool operator != (const db_wallet_sessionid& rhs) const {
            return !(*this == rhs);
        }

        bool operator < (const db_wallet_sessionid&) const;

        uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
        uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

        virtual void printTo(std::ostream& out) const;
    };

    void swap(db_wallet_sessionid& a, db_wallet_sessionid& b);

    std::ostream& operator<<(std::ostream& out, const db_wallet_sessionid& obj);

} // namespace

#endif
