/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef dbc_CONSTANTS_H
#define dbc_CONSTANTS_H

#include "matrix_types.h"

namespace matrix { namespace service_core {

class dbcConstants {
 public:
  dbcConstants();

};

extern const dbcConstants g_dbc_constants;

}} // namespace

#endif
